/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Test {
  public static void doit(SWIGTYPE_p_std__vectorT_long_t v) {
    TestJNI.doit(SWIGTYPE_p_std__vectorT_long_t.getCPtr(v));
  }

}
