
#line 3 "lex.hun_clean.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE hun_cleanrestart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via hun_cleanrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void hun_cleanrestart (FILE *input_file ,yyscan_t yyscanner );
void hun_clean_switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE hun_clean_create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void hun_clean_delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void hun_clean_flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void hun_cleanpush_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void hun_cleanpop_buffer_state (yyscan_t yyscanner );

static void hun_cleanensure_buffer_stack (yyscan_t yyscanner );
static void hun_clean_load_buffer_state (yyscan_t yyscanner );
static void hun_clean_init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER hun_clean_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE hun_clean_scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE hun_clean_scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE hun_clean_scan_bytes (yyconst char *bytes,int len ,yyscan_t yyscanner );

void *hun_cleanalloc (yy_size_t ,yyscan_t yyscanner );
void *hun_cleanrealloc (void *,yy_size_t ,yyscan_t yyscanner );
void hun_cleanfree (void * ,yyscan_t yyscanner );

#define yy_new_buffer hun_clean_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        hun_cleanensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            hun_clean_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        hun_cleanensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            hun_clean_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

#define hun_cleanwrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 67
#define YY_END_OF_BUFFER 68
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[342] =
    {   0,
        4,    3,   68,   67,    4,    2,   67,    5,    6,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,    3,   67,    4,    2,    0,    2,    1,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    3,    0,    0,    1,    0,    0,   19,   19,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,   19,   19,
       19,   19,   19,   19,   21,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   29,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   28,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   19,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   21,    0,    0,
       34,    0,    0,   37,    0,    0,    0,    0,    0,   43,
        0,    0,   47,    0,    0,    0,    0,   52,    0,    0,

        0,    0,   29,    0,    0,   55,    0,    0,    0,    4,
        0,    0,    0,   61,   23,    0,   27,   28,    0,    0,
        0,    0,   65,    0,    3,    0,    2,   19,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
        0,   33,   34,    0,    0,   37,    0,   39,    0,   41,
        0,   43,    0,   46,   47,    0,    0,   51,   30,   52,
       24,    0,   31,    0,    0,    0,   55,    0,    0,   57,
        0,   59,    0,   61,   23,   25,   27,   49,   44,    0,
       64,   65,    0,    1,   19,   32,   33,   35,   36,   38,
       39,   40,   41,   42,   45,   46,   48,   50,   51,   30,

       24,   53,   31,   26,   62,   54,   22,   56,   57,   58,
       59,   60,   25,   49,   44,   63,   64,   66,   20,   32,
       35,   36,   38,   40,   42,   45,   48,   50,   53,   26,
       62,   54,   22,   56,   58,   60,   63,   66,   20,   20,
        0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        3,    3,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    5,    1,    1,    6,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,    1,   17,   18,
        1,   19,    1,    1,   20,   21,   22,   21,   23,   21,
        1,    1,   24,    1,    1,    1,    1,    1,   25,    1,
        1,    1,    1,    1,   26,    1,    1,   27,   28,    1,
        1,    1,    1,    1,    1,    1,   29,   30,   31,   32,

       33,   21,   34,   35,   36,    1,    1,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   47,    1,   27,
       48,   49,    1,    1,    1,    1,    1,   50,    1,   51,
        1,   52,   53,    1,    1,    1,    1,    1,   54,    1,
        1,    1,    1,    1,   55,   56,   57,   58,    1,   59,
       60,    1,   61,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[62] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    3,    1,    1,    4,
        4,    4,    4,    1,    1,    1,    5,    1,    4,    4,
        4,    4,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1
    } ;

static yyconst flex_int16_t yy_base[351] =
    {   0,
        0,   60,  428,  429,    5,   10,  117,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,   18,  388,   23,   28,  387,   33,   38,  386,   20,
       36,  393,   39,   14,   41,   42,  394,   45,  390,   44,
       13,   51,  388,   52,  390,   63,  373,   95,  382,  105,
      388,   96,  377,  385,  101,  375,  383,  395,  157,    0,
      380,  374,  371,  375,  376,  368,  374,  368,  372,  366,
      365,  362,  368,  362,  359,  365,  364,    2,  356,  351,
      359,  359,  347,  355,  341,  356,  348,  348,  353,  347,
      338,  350,  344,  343,  340,  337,  334,  344,  326,  336,

      334,  340,  334,  331,  337,  323,  336,  321,  347,  429,
        0,  163,  169,  116,  346,  316,  318,  323,  327,  312,
      320,  310,  312,  308,  310,  315,  314,  304,  306,  311,
      301,  300,  302,  299,  306,  296,  309,  304,  296,  321,
      301,  290,  298,  297,  287,  289,  290,  284,  286,  291,
      290,  281,  279,  279,  306,  286,  288,  274,  276,  281,
      271,  275,  271,  273,  296,  295,  294,  293,  292,  291,
      290,  289,  288,  287,  286,  285,  284,  429,  255,  268,
      281,  261,  251,  278,  249,  262,  247,  260,  258,  272,
      243,  256,  269,  240,  239,  252,  249,  264,  240,  243,

      241,  244,  429,  244,  230,  257,  237,  227,  240,  185,
      225,  238,  236,  250,  249,  225,  247,  429,  229,  218,
      216,  229,  242,  213,  190,  216,  195,  239,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      222,  237,  429,  216,  219,  429,  218,  233,  216,  231,
      214,  429,  213,  228,  429,  211,  199,  210,  209,  429,
      201,  180,  199,  176,  181,  180,  429,  170,  177,  192,
      170,  183,  162,  429,  429,  173,  429,  168,  161,  144,
      159,  429,  142,  202,  154,  147,  429,  143,  141,  138,
      429,  137,  429,  121,  118,  429,  115,  114,  429,  429,

      429,  112,  429,  110,   89,   84,   79,   78,  429,   76,
      429,   72,  429,  429,  429,   67,  429,   52,   16,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,    6,  429,
      429,  219,  223,  227,  229,  232,  234,  236,  238,  240
    } ;

static yyconst flex_int16_t yy_def[351] =
    {   0,
      342,  342,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,    7,  341,  341,  341,  341,  341,  341,  343,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  344,  344,  345,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,

      341,  341,  341,  341,  341,  341,  341,  341,  346,  341,
      346,  346,  346,  346,  345,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,

      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  348,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  349,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,

      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  350,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  350,  341,
        0,  341,  341,  341,  341,  341,  341,  341,  341,  341
    } ;

static yyconst flex_int16_t yy_nxt[491] =
    {   0,
      341,    5,    6,    5,  341,    7,   24,   25,   24,  341,
       26,   27,   28,   27,  166,   29,  110,    8,    9,   52,
       25,   52,  340,   53,   24,   25,   24,   59,   26,   27,
       28,   27,  340,   29,   27,   28,   27,  133,   29,   55,
       28,   55,   67,   56,   68,   84,   60,  134,   85,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   22,    6,   22,   61,   23,   62,   65,  338,   69,
       73,   70,   74,   77,   81,   78,   82,    8,    9,   86,
       89,   63,   90,  337,   66,   71,   72,   75,  336,   83,
       79,   92,  335,   93,  334,  333,   87,   52,   25,   52,

      332,   53,   55,   28,   55,  331,   56,   94,   95,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   30,  175,  176,   97,  177,  330,   98,  329,   99,
      328,  327,  110,  102,  326,  103,   31,  325,   32,   33,
       34,   35,   36,  100,   37,   38,   39,   40,   41,   42,
      104,   43,   44,  324,  323,   45,   46,  322,   47,  321,
       48,   49,   50,  320,   51,  111,  112,  113,  114,  167,
      110,  168,  169,  110,  318,  317,  316,  315,  170,  110,
      171,  172,  173,  174,  314,  110,   24,   25,   24,  313,
       26,   52,   25,   52,  312,   53,   27,   28,   27,  311,

       29,   24,  310,   55,   28,   55,   52,   56,  309,  308,
      307,   27,  306,  305,  304,  303,  302,  301,   55,    4,
        4,    4,    4,    4,   58,  300,  299,   58,  109,  109,
      115,  298,  115,  165,  165,  228,  228,  285,  285,  319,
      319,  339,  339,  297,  296,  295,  294,  293,  292,  291,
      290,  289,  288,  287,  286,  110,  284,  283,  282,  281,
      280,  279,  278,  277,  276,  275,  274,  273,  272,  271,
      270,  269,  268,  267,  266,  265,  264,  263,  262,  261,
      260,  259,  258,  257,  256,  255,  254,  253,  252,  251,
      250,  249,  248,  247,  246,  245,  244,  243,  242,  241,

      240,  239,  238,  237,  236,  235,  234,  233,  232,  231,
      230,  229,  110,  227,  226,  225,  224,  223,  222,  221,
      220,  219,  218,  217,  216,  215,  214,  213,  212,  211,
      210,  209,  208,  207,  206,  205,  204,  203,  202,  201,
      200,  199,  198,  197,  196,  195,  194,  193,  192,  191,
      190,  189,  188,  187,  186,  185,  184,  183,  182,  181,
      180,  179,  178,  110,  164,  163,  162,  161,  160,  159,
      158,  157,  156,  155,  154,  153,  152,  151,  150,  149,
      148,  147,  146,  145,  144,  143,  142,  141,  140,  139,
      138,  137,  136,  135,  132,  131,  130,  129,  128,  127,

      126,  125,  124,  123,  122,  121,  120,  119,  118,  117,
      116,  110,  108,  107,  106,   54,  105,  101,   96,   91,
       88,   80,   76,   64,   57,   45,   54,  341,    3,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341
    } ;

static yyconst flex_int16_t yy_chk[491] =
    {   0,
        0,    1,    1,    1,    0,    1,    5,    5,    5,    0,
        5,    6,    6,    6,  111,    6,  111,    1,    1,   22,
       22,   22,  339,   22,   24,   24,   24,   30,   24,   25,
       25,   25,  319,   25,   27,   27,   27,   78,   27,   28,
       28,   28,   34,   28,   34,   41,   30,   78,   41,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    2,    2,   31,    2,   31,   33,  318,   35,
       36,   35,   36,   38,   40,   38,   40,    2,    2,   42,
       44,   31,   44,  316,   33,   35,   35,   36,  312,   40,
       38,   46,  310,   46,  308,  307,   42,   52,   52,   52,

      306,   52,   55,   55,   55,  305,   55,   46,   46,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    7,  114,  114,   48,  114,  304,   48,  302,   48,
      298,  297,  114,   50,  295,   50,    7,  294,    7,    7,
        7,    7,    7,   48,    7,    7,    7,    7,    7,    7,
       50,    7,    7,  292,  290,    7,    7,  289,    7,  288,
        7,    7,    7,  286,    7,   59,   59,   59,   59,  112,
      285,  112,  112,   59,  283,  281,  280,  279,  112,  112,
      113,  113,  113,  113,  278,  113,  210,  210,  210,  276,
      210,  225,  225,  225,  273,  225,  227,  227,  227,  272,

      227,  210,  271,  284,  284,  284,  225,  284,  270,  269,
      268,  227,  266,  265,  264,  263,  262,  261,  284,  342,
      342,  342,  342,  342,  343,  259,  258,  343,  344,  344,
      345,  257,  345,  346,  346,  347,  347,  348,  348,  349,
      349,  350,  350,  256,  254,  253,  251,  250,  249,  248,
      247,  245,  244,  242,  241,  228,  226,  224,  223,  222,
      221,  220,  219,  217,  216,  215,  214,  213,  212,  211,
      209,  208,  207,  206,  205,  204,  202,  201,  200,  199,
      198,  197,  196,  195,  194,  193,  192,  191,  190,  189,
      188,  187,  186,  185,  184,  183,  182,  181,  180,  179,

      177,  176,  175,  174,  173,  172,  171,  170,  169,  168,
      167,  166,  165,  164,  163,  162,  161,  160,  159,  158,
      157,  156,  155,  154,  153,  152,  151,  150,  149,  148,
      147,  146,  145,  144,  143,  142,  141,  140,  139,  138,
      137,  136,  135,  134,  133,  132,  131,  130,  129,  128,
      127,  126,  125,  124,  123,  122,  121,  120,  119,  118,
      117,  116,  115,  109,  108,  107,  106,  105,  104,  103,
      102,  101,  100,   99,   98,   97,   96,   95,   94,   93,
       92,   91,   90,   89,   88,   87,   86,   85,   84,   83,
       82,   81,   80,   79,   77,   76,   75,   74,   73,   72,

       71,   70,   69,   68,   67,   66,   65,   64,   63,   62,
       61,   58,   57,   56,   54,   53,   51,   49,   47,   45,
       43,   39,   37,   32,   29,   26,   23,    3,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "hun_clean.flex"
/* hun_clean - karaktereket törlõ, illetve átalakító szûrõ */
/* 2003 (c) Németh László <nemethl@gyorsposta.hu> */
/* Makródefiníciók */
/* Szóköz értékû szekvenciák: szóköz, tabulátor, nem törõ szóköz. */
/* Az &nbsp; entitást, és a ,,kocsi vissza'' karaktert is felvesszük ide */
/* Új sor értékû szekvenciák */
/* A kocsi vissza karaktert az MS-DOS szövegek redundáns kódolása miatt */
/* nem új sor, hanem szóköz értékû karakternek kódoltuk. */
/* \n: új sor */
/* \f: lapdobás */
/* \v: függõleges tabulátor */
#line 670 "lex.hun_clean.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

int hun_cleanlex_init (yyscan_t* scanner);

int hun_cleanlex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int hun_cleanlex_destroy (yyscan_t yyscanner );

int hun_cleanget_debug (yyscan_t yyscanner );

void hun_cleanset_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE hun_cleanget_extra (yyscan_t yyscanner );

void hun_cleanset_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *hun_cleanget_in (yyscan_t yyscanner );

void hun_cleanset_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *hun_cleanget_out (yyscan_t yyscanner );

void hun_cleanset_out  (FILE * out_str ,yyscan_t yyscanner );

int hun_cleanget_leng (yyscan_t yyscanner );

char *hun_cleanget_text (yyscan_t yyscanner );

int hun_cleanget_lineno (yyscan_t yyscanner );

void hun_cleanset_lineno (int line_number ,yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int hun_cleanwrap (yyscan_t yyscanner );
#else
extern int hun_cleanwrap (yyscan_t yyscanner );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  ,yyscan_t yyscanner);
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int hun_cleanlex (yyscan_t yyscanner);

#define YY_DECL int hun_cleanlex (yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

#line 26 "hun_clean.flex"


	/* bekezdéshatárok */
	/* bemenet: legalább két sortörés + szóközök */
	/* kimenet: két sortörés */

	/* A következõkkel nem foglalkozunk: */
	/* XXX Az &nbspvalami szekvenciákból is töröljük az &nbsp-t */

	/* BE: Bekezdéshatárok. A sorokban tabulátorok és szóközök:	 */
	/* BE: 		 */
	/* BE:           */
	/* BE: 	   Vége. */

	/* KI: Bekezdéshatárok. A sorokban tabulátorok és szóközök: */
	/* KI:  */
	/* KI: Vége. */

#line 918 "lex.hun_clean.c"

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			hun_cleanensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				hun_clean_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		hun_clean_load_buffer_state(yyscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 342 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 429 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 44 "hun_clean.flex"
{
		fprintf(yyout, "\n\n");
	}
	YY_BREAK
/* sortörés */
/* bemenet: egy sortörés sorvégi és következõ sor eleji szóközökkel */
/* kimenet: egy sortörés */
/* BE: Sortörés. Szóköz és tabulátor: 	 */
/* BE: 		 Itt is a sor elején. */
/* KI: Sortörés. Szóköz és tabulátor: */
/* KI: Itt is a sor elején. */
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 58 "hun_clean.flex"
{
		fprintf(yyout, "\n");
	}
	YY_BREAK
/* elsõ sor elején lévõ szóközök törlése */
case 3:
YY_RULE_SETUP
#line 63 "hun_clean.flex"

	YY_BREAK
/* szóközsorozat és nem törõ szóközök lecserélése  egy szóközre */
/* bemenet: több szóköz, vagyis SPACE szekvencia egymás után */
/* kimenet: egy szóköz */
/* BE: Szóközsorozat. Több	     	szóköz és   	  tabulátor. */
/* KI: Szóközsorozat. Több szóköz és tabulátor. */
/* BE: Nem törõ szóköz: Vége. */
/* KI: Nem törõ szóköz: Vége. */
case 4:
YY_RULE_SETUP
#line 77 "hun_clean.flex"
{
		fprintf(yyout, " ");
	}
	YY_BREAK
/* < és > átkódolása */
/* bemenet: <, vagy > */
/* kimenet: &lt; vagy &gt; */
/* BE: <> */
/* KI: &lt;&gt; */
case 5:
YY_RULE_SETUP
#line 89 "hun_clean.flex"
{
	fprintf(yyout, "&lt;");
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 93 "hun_clean.flex"
{
	fprintf(yyout, "&gt;");
}
	YY_BREAK
/* Windows karakterkódok egy részének átalakítása */
case 7:
YY_RULE_SETUP
#line 99 "hun_clean.flex"
{ fprintf(yyout, "&euro;"); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 100 "hun_clean.flex"
{ fprintf(yyout, "&lsquor;"); } /* HTML 4.0-ban sbquo; */
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 101 "hun_clean.flex"
{ fprintf(yyout, "&ldquor;"); }  /* HTML 4.0-ban bdquo; */
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 102 "hun_clean.flex"
{ fprintf(yyout, "..."); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 104 "hun_clean.flex"
{ fprintf(yyout, "\""); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 106 "hun_clean.flex"
{ fprintf(yyout, "&lsquo;"); } /* 6 */
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 107 "hun_clean.flex"
{ fprintf(yyout, "&rsquo;"); } /* 9 */
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 108 "hun_clean.flex"
{ fprintf(yyout, "&ldquo;"); } /* 66 */
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 109 "hun_clean.flex"
{ fprintf(yyout, "&rdquo;"); } /* 99 */
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 111 "hun_clean.flex"
{ fprintf(yyout, "&ndash;"); } /* -- */
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 112 "hun_clean.flex"
{ fprintf(yyout, "&mdash;"); } /* --- */
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 114 "hun_clean.flex"
{ fprintf(yyout, "&trade;"); } /* TM */
	YY_BREAK
/* decimális karakterkód */
/* feltesszük, hogy az input latin-2, és a 256-nál kisebb kódok
	/* is erre vonatkoznak. */
/* bemenet: "&" max. 5 jegyû szám és esetleg pontosvesszõ */
/* kimenet: latin-2 karakter, vagy a változatlan kód, illetve */
/* ha a szám a < és > karakterek kódja -> &lt; és &gt; entitás */
/* átkódolásra kerülnek az UNICODE nagykötõjelek, és idézõjelek is */
/* BE: (EEC&#041; (EEC&#041;	&#107	&#60;	&#337;	&#3456;	&#2343235325; */
/* KI: (EEC) (EEC) k &lt; õ &#3456; &#2343235325; */
case 19:
YY_RULE_SETUP
#line 129 "hun_clean.flex"
{
	// decimális karakterkódok kezelése
	// nem latin-1 esetében csak a magyar õÕûÛ
	int i;
	i = atoi(yytext + 2);
	if (i == 38) fprintf(yyout, "&amp;"); // & jel
	else if (i == 60) fprintf(yyout, "&lt;"); // < jel
	else if (i == 62) fprintf(yyout, "&gt;"); // > jel
	else if (i < 256) fprintf(yyout, "%c", i); // latin-1
	else if (i == 337) fprintf(yyout, "õ");
	else if (i == 336) fprintf(yyout, "Õ");
	else if (i == 369) fprintf(yyout, "û");
	else if (i == 368) fprintf(yyout, "Û");
	// ismeretlen kódot nem változtatjuk
	else ECHO;
}
	YY_BREAK
/* Ha hosszabb, mint 5 karakter a szám, nem változtatunk */
case 20:
YY_RULE_SETUP
#line 147 "hun_clean.flex"
{
	ECHO;
}
	YY_BREAK
/* hexadecimális karakterkód */
/* XXX most nem foglalkozunk ezzel (ritka) */
/* BE: &#xF456 &#Xabc; &#xABCDEF; */
/* KI: &#xF456 &#Xabc; &#xABCDEF; */
case 21:
YY_RULE_SETUP
#line 158 "hun_clean.flex"
{
	ECHO;
}
	YY_BREAK
/* XXX speciális és szimbólum HTML 4.0 entitásokkal nem foglalkoztunk még */
/* kivéve a 3 pont, és a &quot; átalakítását */
/* BE: &hellip; */
/* KI: ... */
case 22:
YY_RULE_SETUP
#line 170 "hun_clean.flex"
{ fprintf(yyout, "..."); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 172 "hun_clean.flex"
{ fprintf(yyout, "\""); }
	YY_BREAK
/* magyar idézõjelek: HTML 4.0 -> SGML  */
/* BE: &bdquo; */
/* KI: &ldquor; */
case 24:
YY_RULE_SETUP
#line 180 "hun_clean.flex"
{ fprintf(yyout, "&ldquor;"); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 182 "hun_clean.flex"
{ fprintf(yyout, "&lsquor;"); }
	YY_BREAK
/* latin-1 HTML entitások részleges átalakítása (most még latin-2-re) */
/* átalakítás ott történik, ahol a latin-2 megegyezik a latin-1-gyel */
/* BE: &aacute; &Aacute; &otilde; &Otilde; &ucirc; &Ucirc; &ndash; &mdash; */
/* KI: á Á õ Õ û Û &ndash; &mdash; */
/* "&nbsp"";"? { fprintf(yyout, "%c",(char) 160); } */ // ez már lecserélve */
/* "&iexcl"";"? { fprintf(yyout, "%c",(char) 161); } */ // fordított felkiáltójel
/* "&cent"";"? { fprintf(yyout, "%c",(char) 162); } */
/* "&pound"";"? { fprintf(yyout, "%c",(char) 163); } */
case 26:
YY_RULE_SETUP
#line 198 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 164); }
	YY_BREAK
/* "&yen"";"? { fprintf(yyout, "%c",(char) 165); } */
/* "&brvbar"";"? { fprintf(yyout, "%c",(char) 166); } */
case 27:
YY_RULE_SETUP
#line 203 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 167); }
	YY_BREAK
/* "&uml"";"? { fprintf(yyout, "%c",(char) 168); } */
/* "&copy"";"? { fprintf(yyout, "%c",(char) 169); } */
/* "&ordf"";"? { fprintf(yyout, "%c",(char) 170); } */
/* "&laquo"";"? { fprintf(yyout, "%c",(char) 171); } */
/* "&not"";"? { fprintf(yyout, "%c",(char) 172); } */
/* BE: &shy&shy; */
/* KI:  */
case 28:
YY_RULE_SETUP
#line 215 "hun_clean.flex"
// elválasztási hely jelének (feltételes v. lágy kötõjel) törlése
	YY_BREAK
/* "&reg"";"? { fprintf(yyout, "%c",(char) 174); } */
/* "&macr"";"? { fprintf(yyout, "%c",(char) 175); } */
/* BE: &deg; */
/* KI: ° */
case 29:
YY_RULE_SETUP
#line 224 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 176); } // fokjel, megegyezik latin-2-vel
	YY_BREAK
/* "&plusmn"";"? { fprintf(yyout, "%c",(char) 177); } */
/* "&sup2"";"? { fprintf(yyout, "%c",(char) 178); } */
/* "&sup3"";"? { fprintf(yyout, "%c",(char) 179); } */
/* BE: &acute; */
/* KI: ´ */
case 30:
YY_RULE_SETUP
#line 234 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 180); } // vesszõ ékezet, megegyezik a latin-2-vel
	YY_BREAK
/* "&micro"";"? { fprintf(yyout, "%c",(char) 181); } */
/* "&para"";"? { fprintf(yyout, "%c",(char) 182); } */
/* "&middot"";"? { fprintf(yyout, "%c",(char) 183); } */
/* BE: &cedil; */
/* KI: ¸ */
case 31:
YY_RULE_SETUP
#line 244 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 184); } // cedilla ékezet, megegyezik a latin-2-vel
	YY_BREAK
/* "&sup1"";"? { fprintf(yyout, "%c",(char) 185); } */
/* "&ordm"";"? { fprintf(yyout, "%c",(char) 186); } */
/* "&raquo"";"? { fprintf(yyout, "%c",(char) 187); } */
/* "&frac14"";"? { fprintf(yyout, "%c",(char) 188); } */
/* "&frac12"";"? { fprintf(yyout, "%c",(char) 189); } */
/* "&frac34"";"? { fprintf(yyout, "%c",(char) 190); } */
/* "&iquest"";"? { fprintf(yyout, "%c",(char) 191); } */
/* "&Agrave"";"? { fprintf(yyout, "%c",(char) 192); } */ // betû
/* BE: &Aacute; */
/* KI: Á */
case 32:
YY_RULE_SETUP
#line 259 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 193); }
	YY_BREAK
/* BE: &Acirc; */
/* KI: Â */
case 33:
YY_RULE_SETUP
#line 265 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 194); }
	YY_BREAK
/* "&Atilde"";"? { fprintf(yyout, "%c",(char) 195); } // betû

	/* BE: &Auml; */
/* KI: Ä */
case 34:
YY_RULE_SETUP
#line 273 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 196); }
	YY_BREAK
/* "&Aring"";"? { fprintf(yyout, "%c",(char) 197); } */ // betû
/* "&AElig"";"? { fprintf(yyout, "%c",(char) 198); } */ // betû
/* BE: &Ccedil; */
/* KI: Ç */
case 35:
YY_RULE_SETUP
#line 282 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 199); }
	YY_BREAK
/* "&Egrave"";"? { fprintf(yyout, "%c",(char) 200); } */ // betû
/* BE: &Eacute; */
/* KI: É */
case 36:
YY_RULE_SETUP
#line 290 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 201); }
	YY_BREAK
/* "&Ecirc"";"? { fprintf(yyout, "%c",(char) 202); } */ // betû
/* BE: &Euml; */
/* KI: Ë */
case 37:
YY_RULE_SETUP
#line 298 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 203); }
	YY_BREAK
/* "&Igrave"";"? { fprintf(yyout, "%c",(char) 204); } */ // betû
/* BE: &Iacute; */
/* KI: Í */
case 38:
YY_RULE_SETUP
#line 306 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 205); }
	YY_BREAK
/* BE: &Icirc; */
/* KI: Î */
case 39:
YY_RULE_SETUP
#line 312 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 206); }
	YY_BREAK
/* "&Iuml"";"? { fprintf(yyout, "%c",(char) 207); } */ // betû
/* "&ETH"";"? { fprintf(yyout, "%c",(char) 208); } */ // betû
/* "&Ntilde"";"? { fprintf(yyout, "%c",(char) 209); } */ // betû
/* "&Ograve"";"? { fprintf(yyout, "%c",(char) 210); } */ // betû
/* BE: &Oacute; */
/* KI: Ó */
case 40:
YY_RULE_SETUP
#line 323 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 211); }
	YY_BREAK
/* BE: &Ocirc; */
/* KI: Ô */
case 41:
YY_RULE_SETUP
#line 329 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 212); }
	YY_BREAK
/* XXX Tipikus tévesztés: hullámvonalas O javítása Õ-re */
/* BE: &Otilde; */
/* KI: Õ */
case 42:
YY_RULE_SETUP
#line 337 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 213); }
	YY_BREAK
/* BE: &Ouml; */
/* KI: Ö */
case 43:
YY_RULE_SETUP
#line 343 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 214); }
	YY_BREAK
/* BE: &times; */
/* KI: × */
case 44:
YY_RULE_SETUP
#line 349 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 215); }
	YY_BREAK
/* "&Oslash"";"? { fprintf(yyout, "%c",(char) 216); } */ // betû
/* "&Ugrave"";"? { fprintf(yyout, "%c",(char) 217); } */ // betû
/* BE: &Uacute; */
/* KI: Ú */
case 45:
YY_RULE_SETUP
#line 358 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 218); }
	YY_BREAK
/* XXX Tipikus tévesztés: pontos U javítása Û-re */
/* BE: &Ucirc; */
/* KI: Û */
case 46:
YY_RULE_SETUP
#line 366 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 219); }
	YY_BREAK
/* BE: &Uuml; */
/* KI: Ü */
case 47:
YY_RULE_SETUP
#line 372 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 220); }
	YY_BREAK
/* BE: &Yacute; */
/* KI: Ý */
case 48:
YY_RULE_SETUP
#line 378 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 221); }
	YY_BREAK
/* "&THORN"";"? { fprintf(yyout, "%c",(char) 222); } */ // betû
/* BE: &szlig; */
/* KI: ß */
case 49:
YY_RULE_SETUP
#line 386 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 223); }
	YY_BREAK
/* "&agrave"";"? { fprintf(yyout, "%c",(char) 224); } */ // betû
/* BE: &aacute; */
/* KI: á */
case 50:
YY_RULE_SETUP
#line 394 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 225); }
	YY_BREAK
/* BE: &acirc; */
/* KI: â */
case 51:
YY_RULE_SETUP
#line 400 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 226); }
	YY_BREAK
/* "&atilde"";"? { fprintf(yyout, "%c",(char) 227); } */ // betû
/* BE: &auml; */
/* KI: ä */
case 52:
YY_RULE_SETUP
#line 408 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 228); }
	YY_BREAK
/* "&aring"";"? { fprintf(yyout, "%c",(char) 229); } */ // betû
/* "&aelig"";"? { fprintf(yyout, "%c",(char) 230); } */ // betû
/* BE: &ccedil; */
/* KI: ç */
case 53:
YY_RULE_SETUP
#line 417 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 231); }
	YY_BREAK
/* "&egrave"";"? { fprintf(yyout, "%c",(char) 232); } */ // betû
/* BE: &eacute; */
/* KI: é */
case 54:
YY_RULE_SETUP
#line 425 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 233); }
	YY_BREAK
/* "&ecirc"";"? { fprintf(yyout, "%c",(char) 234); } */ // betû
/* BE: &euml; */
/* KI: ë */
case 55:
YY_RULE_SETUP
#line 433 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 235); }
	YY_BREAK
/* "&igrave"";"? { fprintf(yyout, "%c",(char) 236); } */ // betû
/* BE: &iacute; */
/* KI: í */
case 56:
YY_RULE_SETUP
#line 441 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 237); }
	YY_BREAK
/* BE: &icirc; */
/* KI: î */
case 57:
YY_RULE_SETUP
#line 447 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 238); }
	YY_BREAK
/* "&iuml"";"? { fprintf(yyout, "%c",(char) 239); } */ // betû
/* "&eth"";"? { fprintf(yyout, "%c",(char) 240); } */ // betû
/* "&ntilde"";"? { fprintf(yyout, "%c",(char) 241); } */ // betû
/* "&ograve"";"? { fprintf(yyout, "%c",(char) 242); } */ // betû
/* BE: &oacute; */
/* KI: ó */
case 58:
YY_RULE_SETUP
#line 458 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 243); }
	YY_BREAK
/* BE: &ocirc; */
/* KI: ô */
case 59:
YY_RULE_SETUP
#line 464 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 244); }
	YY_BREAK
/* XXX Tipikus tévesztés: hullámvonalas o javítása õ-re */
/* BE: &otilde; */
/* KI: õ */
case 60:
YY_RULE_SETUP
#line 472 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 245); }
	YY_BREAK
/* BE: &ouml; */
/* KI: ö */
case 61:
YY_RULE_SETUP
#line 478 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 246); }
	YY_BREAK
/* BE: &divide; */
/* KI: ÷ */
case 62:
YY_RULE_SETUP
#line 484 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 247); }
	YY_BREAK
/* "&oslash"";"? { fprintf(yyout, "%c",(char) 248); } */ // betû
/* "&ugrave"";"? { fprintf(yyout, "%c",(char) 249); } */ // betû
/* BE: &uacute; */
/* KI: ú */
case 63:
YY_RULE_SETUP
#line 493 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 250); }
	YY_BREAK
/* BE: &ucirc; */
/* KI: û */
/* XXX Tipikus tévesztés: pontos u javítása û-re */
case 64:
YY_RULE_SETUP
#line 501 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 251); }
	YY_BREAK
/* BE: &uuml; */
/* KI: ü */
case 65:
YY_RULE_SETUP
#line 507 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 252); }
	YY_BREAK
/* BE: &yacute; */
/* KI: ý */
case 66:
YY_RULE_SETUP
#line 513 "hun_clean.flex"
{ fprintf(yyout, "%c",(char) 253); }
	YY_BREAK
/* "&thorn"";"? { fprintf(yyout, "%c",(char) 254); } */ // betû
/* "&yuml"";"? { fprintf(yyout, "%c",(char) 255); } */ // betû
case 67:
YY_RULE_SETUP
#line 517 "hun_clean.flex"
ECHO;
	YY_BREAK
#line 1552 "lex.hun_clean.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * hun_cleanlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( hun_cleanwrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of hun_cleanlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					hun_cleanrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			hun_cleanrestart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) hun_cleanrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 342 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	register char *yy_cp = yyg->yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 342 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 341);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp , yyscan_t yyscanner)
{
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_cp = yyg->yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yyg->yy_hold_char;

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yyg->yy_n_chars + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	yyg->yytext_ptr = yy_bp;
	yyg->yy_hold_char = *yy_cp;
	yyg->yy_c_buf_p = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					hun_cleanrestart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( hun_cleanwrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void hun_cleanrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        hun_cleanensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            hun_clean_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	hun_clean_init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	hun_clean_load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void hun_clean_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		hun_cleanpop_buffer_state();
	 *		hun_cleanpush_buffer_state(new_buffer);
     */
	hun_cleanensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	hun_clean_load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (hun_cleanwrap()) processing, but the only time this flag
	 * is looked at is after hun_cleanwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void hun_clean_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE hun_clean_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) hun_cleanalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in hun_clean_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) hun_cleanalloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in hun_clean_create_buffer()" );

	b->yy_is_our_buffer = 1;

	hun_clean_init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with hun_clean_create_buffer()
 * @param yyscanner The scanner object.
 */
    void hun_clean_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		hun_cleanfree((void *) b->yy_ch_buf ,yyscanner );

	hun_cleanfree((void *) b ,yyscanner );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a hun_cleanrestart() or at EOF.
 */
    static void hun_clean_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	hun_clean_flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then hun_clean_init_buffer was _probably_
     * called from hun_cleanrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void hun_clean_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		hun_clean_load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void hun_cleanpush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	hun_cleanensure_buffer_stack(yyscanner);

	/* This block is copied from hun_clean_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from hun_clean_switch_to_buffer. */
	hun_clean_load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void hun_cleanpop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	hun_clean_delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		hun_clean_load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void hun_cleanensure_buffer_stack (yyscan_t yyscanner)
{
	int num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)hun_cleanalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in hun_cleanensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)hun_cleanrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in hun_cleanensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE hun_clean_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) hun_cleanalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in hun_clean_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	hun_clean_switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to hun_cleanlex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       hun_clean_scan_bytes() instead.
 */
YY_BUFFER_STATE hun_clean_scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return hun_clean_scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to hun_cleanlex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE hun_clean_scan_bytes  (yyconst char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) hun_cleanalloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in hun_clean_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = hun_clean_scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in hun_clean_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE hun_cleanget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int hun_cleanget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int hun_cleanget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *hun_cleanget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *hun_cleanget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int hun_cleanget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *hun_cleanget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void hun_cleanset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void hun_cleanset_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "hun_cleanset_lineno called with no buffer" , yyscanner); 
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void hun_cleanset_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "hun_cleanset_column called with no buffer" , yyscanner); 
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see hun_clean_switch_to_buffer
 */
void hun_cleanset_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void hun_cleanset_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int hun_cleanget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void hun_cleanset_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

/* User-visible API */

/* hun_cleanlex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int hun_cleanlex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) hun_cleanalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* hun_cleanlex_init_extra has the same functionality as hun_cleanlex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to hun_cleanalloc in
 * the yyextra field.
 */

int hun_cleanlex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    hun_cleanset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) hun_cleanalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    hun_cleanset_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from hun_cleanlex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * hun_cleanlex_init()
     */
    return 0;
}

/* hun_cleanlex_destroy is for both reentrant and non-reentrant scanners. */
int hun_cleanlex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		hun_clean_delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		hun_cleanpop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	hun_cleanfree(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        hun_cleanfree(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * hun_cleanlex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    hun_cleanfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *hun_cleanalloc (yy_size_t  size , yyscan_t yyscanner)
{
	return (void *) malloc( size );
}

void *hun_cleanrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void hun_cleanfree (void * ptr , yyscan_t yyscanner)
{
	free( (char *) ptr );	/* see hun_cleanrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 517 "hun_clean.flex"
