/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Tokenizer {
  public static void tokenize(SWIGTYPE_p_std__string instr, SWIGTYPE_p_std__vectorT_std__pairT_long_long_t_t tokens, SWIGTYPE_p_std__vectorT_std__pairT_long_long_t_t whites) {
    TokenizerJNI.tokenize(SWIGTYPE_p_std__string.getCPtr(instr), SWIGTYPE_p_std__vectorT_std__pairT_long_long_t_t.getCPtr(tokens), SWIGTYPE_p_std__vectorT_std__pairT_long_long_t_t.getCPtr(whites));
  }

}
