/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class longArray {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected longArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(longArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TestJNI.delete_longArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public longArray(int nelements) {
    this(TestJNI.new_longArray(nelements), true);
  }

  public int getitem(int index) {
    return TestJNI.longArray_getitem(swigCPtr, this, index);
  }

  public void setitem(int index, int value) {
    TestJNI.longArray_setitem(swigCPtr, this, index, value);
  }

  public SWIGTYPE_p_long cast() {
    long cPtr = TestJNI.longArray_cast(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_long(cPtr, false);
  }

  public static longArray frompointer(SWIGTYPE_p_long t) {
    long cPtr = TestJNI.longArray_frompointer(SWIGTYPE_p_long.getCPtr(t));
    return (cPtr == 0) ? null : new longArray(cPtr, false);
  }

}
