/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Test {
  public static void doit(String msg) {
    TestJNI.doit(msg);
  }

  public static int doit2(SWIGTYPE_p_long v) {
    return TestJNI.doit2(SWIGTYPE_p_long.getCPtr(v));
  }

  public static int doit3(OffsPair offs) {
    return TestJNI.doit3(OffsPair.getCPtr(offs), offs);
  }

  public static void doit4(int[] x) {
    TestJNI.doit4(x);
  }

}
