/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package hu.rilmta.gate.tokenizers.dummyctokenizer;

public class DummyCTokenizerWrapperJNI {
  public final static native long new_IntArray(int jarg1);
  public final static native void delete_IntArray(long jarg1);
  public final static native int IntArray_getitem(long jarg1, IntArray jarg1_, int jarg2);
  public final static native void IntArray_setitem(long jarg1, IntArray jarg1_, int jarg2, int jarg3);
  public final static native long IntArray_cast(long jarg1, IntArray jarg1_);
  public final static native long IntArray_frompointer(long jarg1);
  public final static native void tokenize(String jarg1, int jarg2, int jarg3, long jarg4, long jarg5, int[] jarg6, long jarg7, long jarg8, int[] jarg9);
}
