/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package hu.rilmta.gate.tokenizers.dummyctokenizer;

public class DummyCTokenizerWrapper {
  public static void tokenize(String text, int maxtokens, int maxwhites, SWIGTYPE_p_int token_starts, SWIGTYPE_p_int token_ends, int[] ntokens, SWIGTYPE_p_int white_starts, SWIGTYPE_p_int white_ends, int[] nwhites) {
    DummyCTokenizerWrapperJNI.tokenize(text, maxtokens, maxwhites, SWIGTYPE_p_int.getCPtr(token_starts), SWIGTYPE_p_int.getCPtr(token_ends), ntokens, SWIGTYPE_p_int.getCPtr(white_starts), SWIGTYPE_p_int.getCPtr(white_ends), nwhites);
  }

}
