	/* BE: <s>25.</s> <s>Magyarország */
	/* BE: <s>25.</s> <s>§ */
<s>A 2002.</s> <s>(IV. 25.)</s> <s>
<s>A 25/2002.</s> <s>(IV.</s> <s>25.)</s> <s>
<s>A 25/2002.</s> <s>(IV. 25.)</s> <s>
<s>A 25/2002.</s> <s>(IV.</s> <s>25.)
<s>A 25/2002.</s> <s>(IV.25.)
	/* BE: <s>A 25.</s> <s>§ szerint 2002.</s> <s>IV. havában. */
	/* BE: B.</s> <s>Jenõ. */
A.</s> <s>E.</s> <s>X.</s> <s>Wilson.
XIV.</s> <s>Lajos.
Ott a CD.</s> <s>Hallod?
	/* BE: Pl.</s> <s>Péter és Marcsa pl.</s> <s>25 fánkot is ehetne. */
In apr.</s> <s>I was at Sci.</s> <s>Corp.</s> <s>Mexico.
