	/* BE: Bekezdéshatárok. A sorokban tabulátorok és szóközök:	 */
		
         
	/* BE: 	   Vége. */
	/* BE: Sortörés. Szóköz és tabulátor: 	 */
	/* BE: 		 Itt is a sor elején. */
	/* BE: Szóközsorozat. Több	     	szóköz és   	  tabulátor. */
	/* BE: Nem törõ szóköz: Vége. */
<>
(EEC&#041; (EEC&#041;	&#107	&#60;	&#337;	&#3456;	&#2343235325;
&#xF456 &#Xabc; &#xABCDEF;
&hellip;
&bdquo;
&aacute; &Aacute; &otilde; &Otilde; &ucirc; &Ucirc; &ndash; &mdash;
&shy&shy;
&deg;
&acute;
&cedil;
&Aacute;
&Acirc;
&Auml;
&Ccedil;
&Eacute;
&Euml;
&Iacute;
&Icirc;
&Oacute;
&Ocirc;
&Otilde;
&Ouml;
&times;
&Uacute;
&Ucirc;
&Uuml;
&Yacute;
&szlig;
&aacute;
&acirc;
&auml;
&ccedil;
&eacute;
&euml;
&iacute;
&icirc;
&oacute;
&ocirc;
&otilde;
&ouml;
&divide;
&uacute;
&ucirc;
&uuml;
&yacute;
