	/* BE: Á. A kutya ugat. Jó? */
	/* BE: A kutya ugat. Jó */
	/* BE: lenne, ha abbahagyná! */
	/* BE: Ez itt már */

	/* BE: külön bekezdés! */
	/* BE: "A kutya ugat." &ldquor;Jó?&rdquo; ,,Nem.'' */
	/* BE: N. kormányzósági székhely. */
N.
	/* BE: kormányzósági székhely. */
	/* BE: A www.akármi.hu. */
A mond. folyt.
	/* BE: (mivel?) kisbetûs a folytatás (bizony!)! */
	/* BE: - Nézd a! - mondta az egyik. */
	/* BE: A 4. javítócsomagot. */
	/* BE: 3434/1992. évi elszámolás. */
	/* BE: "Jót s jól! Ebben áll a nagy titok" - figyelmezteti */
	/* BE: Kazinczy költõtársait. */
	/* BE: - Szia Péterkém! Holnap találkozunk - mondta Gizi. */
	/* BE: A "Ne már!"-ral az a baj. */
A WWW.AKARMI.HU.
	/* BE: Azt mondta, hogy "Na!", "Csináld!" és így tovább. */
	/* BE: A macska (családjában a 25.) Katinak nyávogott. */
	/* BE: A Cica 4.0 4. része jó?, Macskák, és más könyvek. */
