	/* BE: <s>-nak, -jaiért, -magyar, bel- */
<s>-e
<s>.edu .HU
<s>red-stars.com
<s>http://www.valami.com
	/* BE: <s>valami.comról */
	/* BE: <s>valami.hu-ról */
<s>http://valami.hu, www.valami.hu/dinnye.html
<s>http://www.valami.com/
<s>http://777sms.com:80
	/* BE: <s>ftp://127.0.0.1:911/Próba/ez-is/macska.jpeg */
<s>/
<s>2.b
<s>3a
<s>paprika.comot
<s>C: c:\
<s>C:\DINNYE\MACSKA.JPG
<s>\\SZERVER\SZOLGALTATAS$
<s>/etc/.././home/
<s>mailto:Macska.Kati@valahol.hu
	/* BE: <s>mailto:Macska.Kati@valahol.huról */
<s>ADMIN$
<s>txt .AVI .bmp.zip
<s>*.doc *.*
<s>1:20:36.7, 4:01,95
<s>1:35
<s>1:3
<s>10-12
<s>1-3
<s>0&ndash;5
<s>-23,12, +12 500, +12.500.000
<s>10.35
<s>2003. 01. 06., 2003-01-06
<s>2003. I. 06., IV. 12.
<s>2003.01.06., IV.12., 05/12, 2003/05/12
<s>25.3
	/* BE: <s>1.1.2. 1.3.128-ból */
<s>133.000.000
<s>123.45/67.
<s>0,99 133,000
<s>1,5-2,5, 1-2,5, 1,5-2
	/* BE: <s>2002-2003., 15.-rõl  */
<s>-0,99% 133,000%-kal 10-20%-kal
	/* BE: <s>5°, °C */
<s>600&yen;2400
<s>12 500,1 231, 12.500,12 
	/* BE: <s>63 millió, 23 ezerrõl, 3 ezret, 23 milliárdosnak, 1,5-2,5 milliót */
<s>1645kJ/1000g 1645 kJ/100 g
<s>800x600, 12&times; 1x2x3x4
<s>MSZ EN ISO 30011-2:1993, MSZ-09-10.0346:1990
<s>ISBN 0-7201-2270-8
	/* BE: <s>5/4, 5/4-ét */
<s>M5, TU&ndash;154
<s>45654/1994/3.,
<s>1/A, 41/J.,
<s>III/1
<s>IV/c
	/* BE: <s>2000/45.-rõl */
	/* BE: <s>06 (20) 477-4917, 47-55-45/25-rõl */
<s>21559468-1-06
<s>JA51BF26X5H345328
<s>BDE/2000/01/0983/0010
<s>802.11b
<s>BH1992.,
<s>iii)
<s>(iii)
<s>a), ( A )
<s>(iii)-(viii)
<s>a)-d)]
<s>(1)-(4)
<s>2r&pi;, 2 * 2 = 4, (a+b)(a-b), 36-os
	/* BE: <s>Az "Íme, hát megleltem hazámat"-ban írta. */
<s>:-)
<s>"!"&ldquor;
<s>Stb... stb...
<s>Pl. nagy.
<s>stb.
<s>stb.)
	/* BE: <s>Jó... Is.... */
<s>S.M.A.R.T.
<s>Lakik-e?
<s>7-es
<s>&#8222;
<s>bel-, Dinnye-domb-
	/* BE: <s>§-sal */
	/* BE: <s>Moli&egrave;re-rõl beszélj! */
	/* BE: <s>CD-ROM-okról */
	/* BE: <s>X.25-rõl */
	/* BE: <s>(Ki)adós fizess(en) könyv(ek)et? */
<s>AT&T
<s>don't
	/* BE: <s>A-B100, A-B100-ról */
<s>.bash_rc, .dinnye.macska.25
	/* BE: <s>.hu-ról .hu-i .hu-iról .hu-nkról .hu-inkról .hu-éról .hu-éiról .hu-inkéról .hu-inkéiról */
<s>Hogue-t,
